describe('Employee-specific configuration', () => {
  test.todo('clones down boilerplate-extras repo')
  test.todo('moves terraform into place')
  test.todo('moves makefiles into place')
  test.todo('moves appropriate buildspec into place')
  test.todo('extends readme')
  test.todo('removes boilerplate-extra folder')
  test.todo('writes project name to Makefiles (API and Frontend)')
  test.todo('uses project name for Helm repository')
  test.todo('uses project name for Helm subdomain')
})
