describe('Base docker compose configuration', () => {
  test.todo('can set docker-compose db type to postgres')
  test.todo('can set docker-compose db type to mysql')
  test.todo('sets docker-compose db port')
  test.todo('sets docker-compose db user')
  test.todo('sets docker-compose db pass')
  test.todo('sets docker-compose db name')
  test.todo('sets docker-compose db root password when mysql')
  test.todo('configures images names')
})
